from core.views.project_view import ProjectViewSet
from core.views.ppap_view import PPAPViewSet
from core.views.phase_view import PhaseViewSet
from core.views.output_view import OutputViewSet
from core.views.document_view import DocumentViewSet
from core.views.user_view import UserViewSet
from core.views.client_view import ClientViewSet
from core.views.team_view import TeamViewSet
from core.views.history_view import HistoryViewSet
