# Generated by Django 4.2.7 on 2025-04-30 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('history_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('history_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'authorization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('code', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_id', models.CharField(max_length=100, unique=True)),
                ('history_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'client',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('history_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'contact',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('history_id', models.CharField(max_length=100, unique=True)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('history_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('event', models.TextField()),
                ('table_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Not Started', max_length=50)),
                ('history_id', models.CharField(max_length=100, unique=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='core.document')),
            ],
            options={
                'db_table': 'output',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'permission',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhaseTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'phase_template',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PPAP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('status', models.CharField(default='Not Started', max_length=50)),
                ('review', models.TextField(blank=True, null=True)),
                ('history_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ppap',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PPAPElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ppap_element',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'team',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='core.output')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='core.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'todo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Planning', max_length=50)),
                ('history_id', models.CharField(max_length=100, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.client')),
                ('ppap', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_project', to='core.ppap')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.team')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='ppap',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppaps', to='core.project'),
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Not Started', max_length=50)),
                ('history_id', models.CharField(max_length=100, unique=True)),
                ('ppap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='core.ppap')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_phases', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='core.phasetemplate')),
            ],
            options={
                'db_table': 'phase',
                'ordering': ['template__order'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_id', models.CharField(max_length=100, unique=True)),
                ('is_user', models.BooleanField(default=False)),
                ('history_id', models.CharField(max_length=100, unique=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.department')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.team')),
            ],
            options={
                'db_table': 'person',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OutputTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('configuration', models.JSONField(default=dict)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_templates', to='core.phasetemplate')),
                ('ppap_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_templates', to='core.ppapelement')),
            ],
            options={
                'db_table': 'output_template',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='output',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='core.phase'),
        ),
        migrations.AddField(
            model_name='output',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='core.outputtemplate'),
        ),
        migrations.AddField(
            model_name='output',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_outputs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FastQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.JSONField(default=dict)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fastquery', to='core.project')),
            ],
            options={
                'db_table': 'fastquery',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.output'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='authorization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.authorization'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.person'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
