# Generated by Django 4.2.7 on 2025-05-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_user_team',
            field=models.BooleanField(default=False, help_text='True for user teams, False for client teams'),
        ),
    ]
