# Generated by Django 4.2.7 on 2025-04-30 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('history_id', models.CharField(max_length=100, unique=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_roles', to='core.person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='core.team')),
            ],
            options={
                'db_table': 'team_member_role',
                'unique_together': {('person', 'team')},
            },
        ),
    ]
