const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"

export const API_ENDPOINTS = {
  projects: `${API_BASE_URL}/projects/`,
  ppaps: `${API_BASE_URL}/ppaps/`,
  phases: `${API_BASE_URL}/phases/`,
  outputs: `${API_BASE_URL}/outputs/`,
  documents: `${API_BASE_URL}/documents/`,
  users: `${API_BASE_URL}/users/`,
  clients: `${API_BASE_URL}/clients/`,
  teams: `${API_BASE_URL}/teams/`,
  history: `${API_BASE_URL}/history/`,
  persons: `${API_BASE_URL}/persons/`,
  contacts: `${API_BASE_URL}/contacts/`,
  departments: `${API_BASE_URL}/departments/`,
  phaseTemplates: `${API_BASE_URL}/phase-templates/`,
  outputTemplates: `${API_BASE_URL}/output-templates/`,
  ppapElements: `${API_BASE_URL}/ppap-elements/`,
  authorizations: `${API_BASE_URL}/authorizations/`,
  todos: `${API_BASE_URL}/todos/`,
  authLogin: `${API_BASE_URL}/auth/login/`,
  authLogout: `${API_BASE_URL}/auth/logout/`,
  authUser: `${API_BASE_URL}/auth/user/`,
  dashboard: `${API_BASE_URL}/dashboard/`,
  userPermissions: `${API_BASE_URL}/user-permissions/`,
  changeStatus: `${API_BASE_URL}/change-status/`,
  assignPermission: `${API_BASE_URL}/assign-permission/`,
  assignPhaseResponsible: `${API_BASE_URL}/assign-phase-responsible/`,
}
