from core.models.history import History
from core.models.project.project import Project
from core.models.project.client import Client
from core.models.project.fastquery import FastQuery
from core.models.ppap.ppap import PPAP
from core.models.ppap.element import PPAPElement
from core.models.phase.phase import Phase
from core.models.phase.template import PhaseTemplate
from core.models.output.output import Output
from core.models.output.template import OutputTemplate
from core.models.output.document import Document
from core.models.organization.team import Team
from core.models.organization.department import Department
from core.models.organization.todo import Todo
from core.models.organization.user import User
from core.models.other.person import Person
from core.models.other.contact import Contact
from core.models.other.permission import Permission
from core.models.other.authorization import Authorization
